exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "vendor", "Gemfile", "Gemfile.lock", "Guardfile", "assets.yml"]
highlighter: pygments

title: Citi Bike | Your bike sharing system in New York City and Jersey City
description: The Citi Bike system features thousands of bikes at hundreds of stations around New York City and Jersey City. Citi Bikes are available 24/7, 365 days a year.
url: https://www.citibikejc.com
google-site-verification: TODO
ga: UA-17974252-20

sass:
  style: :compressed
  sass_dir: assets/stylesheets

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "smart"]

membership-enabled: true
post-enabled: true
login-enabled: true
corporate-partners-enabled: false
map-link-enabled: true

collections:
  memberships:
    output: false

text:
  twitter: https://twitter.com/CitiBikeJC
  facebook: https://www.facebook.com/CitiBikeJC
  instagram: https://instagram.com/citibikejc

  city-name: Jersey City
  hero-heading: Citi Bike is rolling into Jersey City...
  hero-subheading: Hear the news as it happens
  hero-button: stay informed
  hero-image-url: /assets/images/jc-background.jpg
  signup-form-url: '//citibikejc.us11.list-manage.com/subscribe/post?u=db9922af61b48a75cbb0edf87&amp;id=5a1ba0a364'
  signup-form-secret: b_db9922af61b48a75cbb0edf87_5a1ba0a364

  login-link: https://member.citibikenyc.com/profile/login
  signup-link: https://member.citibikenyc.com/offers/newmembers?promotion=jerseycity&code=citibikejc

  sponsors-title: A Thanks To Our Sponsors
  sponsors-left: Title Sponsor
  sponsors-right: Founding Partners

  post-heading: Citi to Become Title Sponsor for Jersey City’s Bike Share Program
  post-subheading: FOR IMMEDIATE RELEASE
  post-date: August 4, 2015
  post-link: http://www.motivateco.com/news/2015/08/04/citi-to-become-title-sponsor-for-jersey-citys-bike-share-program
  post-body: "
    _Additional sponsors include Horizon, SUEZ North America, CarePoint, and Jersey City Medical Center – Barnabas Health_


    _Program will create new, affordable transportation option for Jersey City and be interoperable with New York City’s Citi Bike program_


    Jersey City—Mayor Steven Fulop and Jay Walder, President & CEO of Motivate, announced sponsors for Jersey City’s new bike share program launching in September. Citi will be the Title Sponsor, and the bike share program will be named Citi Bike. Citi Bike Jersey City and Citi Bike New York will be interoperable programs, meaning membership to one will entitle riders to the same usage in sister market. Four additional organizations– the Horizon Foundation for New Jersey, SUEZ North America, CarePoint Health and Jersey City Medical Center–Barnabas Health have been named Founding Sponsors. The program’s website www.citibikejc.com launched today as well.
    "

  map-title: coming soon
  map-image-url: /assets/images/map.png
  map-link: https://member.citibikenyc.com/map/

  rides-title: 3 Different Ways to Ride

  corporate-title: Corporate Memberships
  corporate-body: Is your organization looking for a fun way to enhance the health and happiness of its employees? Citi Bike is here to help. Sign up today as a corporate and community partner and give your employees free access to thousands of bikes at hundreds of stations throughout Jersey City, Manhattan, Brooklyn and coming soon — Queens. Citi Bike is a great option for commuting as well as running errands or sneaking in a little extra exercise into our busy lives — and it’s a great way to demonstrate your corporate commitment to wellness.
  corporate-button: get your org on board
  corporate-link: https://docs.google.com/a/motivateco.com/forms/d/1BcQQR9WDVTZ1PEcgc5QLXTBXzwny8Eb27aAjXoKOIJE/viewform
  corporate-learn-more-link: https://www.citibikenyc.com/assets/pdf/Citi_Bike_Jersey_City_Charter_Corporate_Partner.pdf
  corporate-extra: "Our Charter Corporate Partners"
  corporate-learn-button: learn more
  corporate-learn-link: https://www.citibikenyc.com/assets/pdf/Citi_Bike_Jersey_City_Charter_Corporate_Partner.pdf

  bottom-footer: Use of this Website constitutes acceptance of the [Website Terms of Use Agreement](http://www.citibikenyc.com/terms-of-use) and [Privacy Policy](http://www.citibikenyc.com/privacy)
  bottom-footer-copyright: "Copyright 2013 - 2015 Motivate International, Inc. All rights reserved.<br />
    Citi, Citi with Arc Design and Citi Bike are registered trademarks of Citigroup, Inc
    "
